// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1LbW_FIuDf3bAcZTWqLlXH1mt3dQHbI',
    appId: '1:648185224078:web:3b20b37a1ef6d42a9862df',
    messagingSenderId: '648185224078',
    projectId: 'todoapp-a4f67',
    authDomain: 'todoapp-a4f67.firebaseapp.com',
    storageBucket: 'todoapp-a4f67.firebasestorage.app',
    measurementId: 'G-5H1YDQ97EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_zl9zCasO3JIHHkTED6ClRQwAM2SUEc',
    appId: '1:648185224078:android:cf3d4f093150edd09862df',
    messagingSenderId: '648185224078',
    projectId: 'todoapp-a4f67',
    storageBucket: 'todoapp-a4f67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXAfw3_ueQjgxiHzol5iH2AQW8uC46sL4',
    appId: '1:648185224078:ios:1d04a650c6eae0c09862df',
    messagingSenderId: '648185224078',
    projectId: 'todoapp-a4f67',
    storageBucket: 'todoapp-a4f67.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXAfw3_ueQjgxiHzol5iH2AQW8uC46sL4',
    appId: '1:648185224078:ios:1d04a650c6eae0c09862df',
    messagingSenderId: '648185224078',
    projectId: 'todoapp-a4f67',
    storageBucket: 'todoapp-a4f67.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ1LbW_FIuDf3bAcZTWqLlXH1mt3dQHbI',
    appId: '1:648185224078:web:aeddb7421cc048069862df',
    messagingSenderId: '648185224078',
    projectId: 'todoapp-a4f67',
    authDomain: 'todoapp-a4f67.firebaseapp.com',
    storageBucket: 'todoapp-a4f67.firebasestorage.app',
    measurementId: 'G-MGR8SX08ED',
  );
}
